TR12734/GenFeVah/TSS

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -67,5 +67,43 @@ then
     mkdir -p ${INPUTDIR}
 fi
 
+# copy the scripts for curator use into a standard location which exists in
+# their path statements
+
+# trim any trailing slash from MGIBIN variable
+DEPLOY_PATH=`echo "${MGIBIN}" | sed 's./$..'`
+
+if [ "${DEPLOY_PATH}" = "" ]; then
+        echo "Warning: MGIBIN variable missing from mgiconfig; cannot deploy curator files"
+        exit 0
+fi
+
+if [ ! -d ${DEPLOY_PATH} ]; then
+        # failure to deploy is not a fatal error; could happen during
+        # development under a home directory
+        echo "Warning: ${DEPLOY_PATH} does not exist; curator scripts were not copied."
+        exit 0
+fi
+
+if [ -d ${DEPLOY_PATH} ]; then
+        # copy files, change permissions, and check for errors
+        # deployment errors are non-fatal, as they can occur regularly in an
+        # SE's development area
+
+        for file in runTssGeneQC publishTssGene
+        do  
+                cp bin/${file} ${DEPLOY_PATH}
+                if [ $? -ne 0 ]; then
+                        echo "Warning: Failed to copy ${file} to ${DEPLOY_PATH}"
+                fi  
+
+                chmod 755 ${DEPLOY_PATH}/${file}
+                if [ $? -ne 0 ]; then
+                        echo "Warning: Failed to change permissions on ${DEPLOY_PATH}/${file}"
+                fi  
+        done
+        echo "Deployed curator files to ${DEPLOY_PATH}"
+fi
+
 exit 0
 
